### ISSUE TITLE
example eth_sendTransaction

### ISSUE THREAD

**Issue by truongthaison** [petrhejna/geth-jsonrpc-php-client#10]
Hi, 
How to call method: eth_sendTransaction,
i get code: -32602, "invalid argument 0: json: cannot unmarshal string into Go value of type ethapi.SendTxArgs"

Please help me

**Comment by deanshelton913** [comment]
lol "please help me"
You sound like you're hurtin', man.
Your error is coming from GoLang trying to parse (aka: unmarshal) your input into a Golang Struct with json annotations. 
Check out the actual struct it is trying to unmarshal into, and compare it with the JSON payload you are sending. Note the variable types. A 0 must be being passed somewhere where it's not supposed to be

https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go#L1258
