### ISSUE TITLE
Fatal error on Class GuzzleClient

### ISSUE THREAD

**Issue by mbsaberi** [petrhejna/geth-jsonrpc-php-client#12]
Hi. I've installed your project on my server and ran the codes. But this error happened:
`Fatal error: Uncaught Error: Class 'GuzzleClient' not found in ...`

May you check it out please?

**Comment by petrhejna** [comment]
Hi, can you please provide full error message?
Thanks

**Comment by petrhejna** [comment]
Closing for now, It you have some more info, I'll happily reopen.
